var missions = {
  lockdown_12: {
    state: "CLOSED",
    system: "INCIDENT FILE // LOCKDOWN 12 // TACTICAL",
    title: "LOCKDOWN 12",
    sub: "FILE // 2021 • STATE // CLOSED",
    clearance: "ACCÈS TACTIQUE",
    theatre: "ZONE URBAINE",
    risk: "CRITIQUE",
    context: "Intervention déclenchée sur une prise d’otages dans un immeuble résidentiel à forte densité. Tout avait commencé comme une dispute de voisinage mal comprise, avant que les premiers appels ne fassent remonter la même image : une silhouette enfermée derrière une porte d’angle, une arme visible par intermittence, et des voix étouffées que personne n’arrivait à distinguer clairement. Lorsque Saul est arrivé sur zone, la rue était déjà passée du chaos au silence brutal, celui qui tombe quand tout le monde comprend qu’un seul geste de trop peut faire basculer la nuit.",
    timeline: [
      "Déploiement immédiat du périmètre et isolement des accès verticaux du bâtiment.",
      "Évaluation initiale de la menace par canal de négociation et collecte des informations de voisinage.",
      "Échec d’une première tentative de désescalade après comportement incohérent du suspect.",
      "Préparation d’une entrée contrôlée avec progression en couloir étroit et environnement civil encombré.",
      "Breach coordonné sur point d’accès principal avec maintien simultané d’un axe de couverture secondaire.",
      "Neutralisation du suspect au contact après menace immédiate sur un otage rapproché.",
      "Extraction et sécurisation des civils avant remise de la scène aux équipes d’enquête."
    ],
    outcome: "Menace neutralisée. Les otages sont sortis tremblants, incapables de mesurer à quel point tout s’était joué vite. Dans le rapport final, l’intervention est classée efficace ; dans les mémoires d’équipe, elle reste surtout comme l’une de ces nuits où la maîtrise n’a tenu qu’à quelques secondes de lucidité intacte.",
    arrest: "SUSPECT DÉCÉDÉ SUR LES LIEUX",
    civilian: "AUCUNE VICTIME PARMI LES CIVILS",
    evidence: "ARME DE POING / DISPOSITIFS DE CONTRAINTE / COMMUNICATIONS",
    review: "USAGE DE LA FORCE JUSTIFIÉ",
    dispatch: "Premier appel reçu à 22:14. Multiples voix signalées derrière porte close. Arme aperçue par voisin du palier.",
    witness: "« On n’entendait plus que ses pas dans l’appartement. C’était pire quand il arrêtait de parler. »",
    attachment: "ANNEXE 12-A SCELLÉE // PLAN D’ÉTAGE ET CAPTURES CAMÉRA COULOIR",
    note: "Dossier utilisé en interne comme référence pour la gestion d’entrée en structure résidentielle avec otages multiples."
  },

  harbor_nine: {
    state: "CLOSED",
    system: "INCIDENT FILE // HARBOR NINE // TACTICAL",
    title: "HARBOR NINE",
    sub: "FILE // 2023 • STATE // CLOSED",
    clearance: "ACCÈS TACTIQUE",
    theatre: "ZONE PORTUAIRE",
    risk: "ÉLEVÉ",
    context: "Opération conduite dans une zone portuaire après identification d’un point de rendez-vous utilisé pour un échange d’armes. La scène n’avait presque rien d’humain : des couloirs de métal, des projecteurs sales, l’eau noire en arrière-plan et, partout, cette impression que les silhouettes n’existaient vraiment qu’au moment où elles traversaient la lumière. Le danger ne tenait pas seulement à l’armement du groupe, mais à sa capacité à se dissoudre instantanément dans les quais, les conteneurs et les routes latérales.",
    timeline: [
      "Mise en place d’un dispositif discret sur les voies d’accès au quai secondaire.",
      "Confirmation visuelle de plusieurs individus armés à proximité d’un véhicule utilitaire.",
      "Synchronisation de l’intervention afin d’éviter toute fuite par les voies latérales du secteur portuaire.",
      "Annonce police et tentative de reddition immédiatement suivies d’un mouvement hostile.",
      "Neutralisation rapide de la menace principale et contrôle des individus secondaires.",
      "Sécurisation du véhicule, saisie d’armes longues et de caisses logistiques.",
      "Nettoyage de zone et remise du site aux unités d’enquête spécialisées."
    ],
    outcome: "Cibles interpellées ou neutralisées selon règles d’engagement. Le site a été repris vite, mais la tension a continué de coller à l’opération bien après sa fin, comme si le port lui-même gardait encore l’empreinte de cette nuit.",
    arrest: "PLUSIEURS INTERPELLATIONS / MENACE PRINCIPALE NEUTRALISÉE",
    civilian: "AUCUNE IMPLICATION DE CIVILS",
    evidence: "FUSILS / MUNITIONS / ÉLÉMENTS LOGISTIQUES VÉHICULE",
    review: "INTERVENTION TACTIQUE CONFORME AUX DIRECTIVES",
    dispatch: "Véhicule suspect observé à 01:07. Mouvements de chargement confirmés par surveillance amont.",
    witness: "« Je pensais que c’était juste des dockers. Puis j’ai vu la manière dont ils surveillaient les accès. »",
    attachment: "ANNEXE 09-C SCELLÉE // INVENTAIRE PARTIEL DES SAISIES",
    note: "La rapidité du verrouillage périphérique a empêché toute dispersion du groupe. Rapport tactique noté favorable."
  },

  glass_hall: {
    state: "CLOSED",
    system: "INCIDENT FILE // GLASS HALL // TACTICAL",
    title: "GLASS HALL",
    sub: "FILE // 2024 • STATE // CLOSED",
    clearance: "ACCÈS TACTIQUE",
    theatre: "CENTRE ADMINISTRATIF",
    risk: "ÉLEVÉ",
    context: "Intervention déclenchée dans un ensemble administratif moderne presque entièrement vitré. Dès l’extérieur, tout semblait visible ; à l’intérieur, plus rien ne l’était réellement. Les reflets effaçaient les distances, les cloisons coupaient la lecture des volumes, et le moindre mouvement humain se doublait de sa propre illusion. Les premiers employés évacués parlaient vite, contradictoirement, comme si le bâtiment lui-même avait troublé leur perception.",
    timeline: [
      "Mise en sécurité du périmètre extérieur et évacuation des abords directs du bâtiment.",
      "Consolidation des témoignages contradictoires transmis par le personnel évacué.",
      "Entrée tactique par niveau inférieur afin d’éviter les surfaces les plus exposées.",
      "Progression par paliers successifs dans une structure à visibilité trompeuse.",
      "Localisation de plusieurs personnes confinées dans des espaces de travail fermés.",
      "Contact final avec la menace dans une zone de circulation vitrée à visibilité instable.",
      "Neutralisation de la situation et sortie progressive des employés encore présents."
    ],
    outcome: "Le bâtiment a été repris sans victime civile et la panique initiale a pu être contenue avant de se transformer en mouvement de foule. Le rapport final insiste sur la capacité de l’équipe à ne jamais se laisser aspirer par le faux sentiment de contrôle que donnait l’architecture.",
    arrest: "SUSPECT MAÎTRISÉ ET PLACÉ EN DÉTENTION",
    civilian: "PERSONNELS EXTRAITS SANS BLESSURE",
    evidence: "ARME DE POING / BADGE D’ACCÈS / TÉLÉPHONE CHIFFRÉ",
    review: "INTERVENTION VALIDÉE",
    dispatch: "Alerte interne déclenchée à 18:42. Dernier étage indiqué comme point de repli probable.",
    witness: "« On le voyait partout dans les vitres, sans savoir où il était vraiment. »",
    attachment: "ANNEXE 04-D SCELLÉE // SCHÉMA D’INTERVENTION PAR NIVEAUX",
    note: "Cas régulièrement cité pour l’étude des environnements modernes à transparence trompeuse."
  },

  dead_air: {
    state: "CLOSED",
    system: "INCIDENT FILE // DEAD AIR // TACTICAL",
    title: "DEAD AIR",
    sub: "FILE // 2025 • STATE // CLOSED",
    clearance: "ACCÈS TACTIQUE",
    theatre: "SITE ISOLÉ",
    risk: "ÉLEVÉ",
    context: "Le signalement initial était presque vide : une ancienne station radio, des allées et venues observées à distance, des transmissions brèves repérées sur une fréquence morte depuis des années. Ce genre d’endroit attire tout ce que la ville préfère ne plus regarder : les gens qui s’effacent, les trafics qui s’installent dans le silence, les histoires qui ne remontent jamais complètement jusqu’aux dossiers.",
    timeline: [
      "Approche discrète du site avec maintien d’une signature opérationnelle minimale.",
      "Reconnaissance extérieure et vérification des points d’entrée encore utilisables.",
      "Pénétration lente dans le bâtiment principal en environnement faiblement éclairé.",
      "Découverte de zones techniques réactivées malgré l’abandon apparent du site.",
      "Contact bref mais immédiat avec un individu armé à proximité de l’ancien poste central.",
      "Sécurisation successive des niveaux inférieurs et des annexes de transmission.",
      "Clôture de l’intervention après reprise complète du site et gel des accès."
    ],
    outcome: "La station a été sécurisée, plusieurs éléments de communication ont été saisis et la présence armée sur site démantelée. Le dossier reste moins spectaculaire que d’autres, mais il raconte mieux que beaucoup l’épaisseur du silence dans lequel certaines violences choisissent de s’installer.",
    arrest: "PLUSIEURS SUSPECTS EN DÉTENTION",
    civilian: "AUCUNE PRÉSENCE CIVILE RECENSÉE",
    evidence: "MATÉRIEL RADIO / ARMES / SUPPORTS NUMÉRIQUES",
    review: "CONFORME AUX PROCÉDURES",
    dispatch: "Signal radio parasite détecté sur fréquence morte. Activité humaine confirmée visuellement à 02:11.",
    witness: "« De loin, on aurait juré que le bâtiment était vide. C’est ça qui le rendait inquiétant. »",
    attachment: "ANNEXE 17-B SCELLÉE // EXTRAITS DE FRÉQUENCES CAPTÉES",
    note: "Le site reste mentionné en interne comme référence pour les interventions en structure abandonnée réactivée."
  },

  ivory_line: {
    state: "CLOSED",
    system: "INCIDENT FILE // IVORY LINE // TACTICAL",
    title: "IVORY LINE",
    sub: "FILE // 2024 • STATE // CLOSED",
    clearance: "ACCÈS TACTIQUE",
    theatre: "IMMEUBLE RÉSIDENTIEL",
    risk: "ÉLEVÉ",
    context: "Le dossier semblait bref : un appartement verrouillé, un mineur potentiellement retenu, très peu d’informations exploitables. Pourtant, ce sont souvent les interventions les plus petites qui pèsent le plus lourd. Il n’y avait ni foule, ni bruit de scène ouverte, seulement une porte close, un couloir trop étroit, et ce sentiment physique d’arriver trop tard alors même que rien n’était encore perdu.",
    timeline: [
      "Recueil des informations de voisinage et vérification rapide des accès intérieurs.",
      "Écoute de proximité sur porte fermée sans retour clair de l’intérieur.",
      "Mise en place d’une entrée contrainte avec extraction immédiate prévue.",
      "Ouverture forcée de l’appartement et sécurisation des premières pièces.",
      "Localisation du mineur dans une chambre secondaire verrouillée.",
      "Maîtrise rapide de l’adulte présent sur zone.",
      "Sortie protégée et transfert aux services compétents."
    ],
    outcome: "Le mineur a été extrait vivant, choqué mais indemne. La mission reste classée parmi les fermées, mais elle garde une charge intime particulière : celle des interventions qui se jouent à très petite échelle et laissent pourtant derrière elles un silence immense.",
    arrest: "SUSPECT INTERPELLÉ",
    civilian: "MINEUR EXTRAIT SANS BLESSURE",
    evidence: "CLÉS / TÉLÉPHONE / DISPOSITIFS DE CONTRAINTE",
    review: "INTERVENTION VALIDÉE",
    dispatch: "Appel voisinage transmis sans visibilité directe. Présence d’un enfant fortement suspectée.",
    witness: "« On n’entendait rien. C’est ce silence-là qui nous a fait appeler. »",
    attachment: "ANNEXE 21-A SCELLÉE // NOTE PROTECTION MINEUR",
    note: "Dossier relu en formation pour la gestion d’entrée contrainte en environnement domestique très réduit."
  },

  night_warrant: {
    state: "ARCHIVED",
    system: "INCIDENT FILE // NIGHT WARRANT // INTERNAL",
    title: "NIGHT WARRANT",
    sub: "FILE // 2022 • STATE // ARCHIVED",
    clearance: "ACCÈS INTERNE",
    theatre: "ZONE PÉRIURBAINE",
    risk: "ÉLEVÉ",
    context: "Exécution d’un mandat d’arrêt sur un individu suspecté de trafic d’armes et de détention d’équipements non déclarés. La maison n’avait rien d’impressionnant. C’est précisément ce qui inquiétait. Certaines portes n’affichent rien d’autre qu’une façade banale, une clôture fatiguée et une lumière trop faible ; pourtant, derrière, le risque s’est parfois organisé plus méthodiquement qu’ailleurs.",
    timeline: [
      "Surveillance préalable des flux autour de la résidence afin d’identifier routine et points d’accès.",
      "Déploiement discret des équipes sur le périmètre immédiat avant fenêtre d’intervention nocturne.",
      "Entrée contrôlée sur la structure principale après validation de présence de la cible.",
      "Résistance armée brève dans un couloir secondaire immédiatement contenue par l’équipe d’appui.",
      "Contrôle complet du bâtiment et identification de compartiments de stockage non visibles depuis l’entrée.",
      "Saisie d’armes, de munitions et de documentation associée au trafic.",
      "Extraction de la cible et sécurisation de la scène pour exploitation judiciaire."
    ],
    outcome: "Mandat exécuté avec succès. Ce qui devait être une intervention rapide a révélé un point de stockage plus structuré que prévu, donnant au dossier une portée supérieure à celle du simple mandat initial. Archivé, il continue d’être relu comme on relit les missions qui ont appris à l’équipe à se méfier de ce qui paraît trop ordinaire.",
    arrest: "CIBLE PRINCIPALE PLACÉE EN GARDE À VUE",
    civilian: "AUCUN BLESSÉ CIVIL SIGNALÉ",
    evidence: "ARMES À FEU / ESPÈCES / DOCUMENTS LIÉS AU TRAFIC",
    review: "EXÉCUTION CONFORME AUX NORMES / AUCUNE VIOLATION DES DIRECTIVES",
    dispatch: "Mandat exécutif confirmé à 03:40. Occupation simple supposée avant découverte des compartiments.",
    witness: "« Rien ne distinguait cette maison des autres. C’était presque ça le pire. »",
    attachment: "ANNEXE 03-F SCELLÉE // INVENTAIRE STOCKAGE CLANDESTIN",
    note: "Le dossier reste archivé comme cas d’école pour les entrées résidentielles sensibles."
  },

  redline_yard: {
    state: "ARCHIVED",
    system: "INCIDENT FILE // REDLINE YARD // INTERNAL",
    title: "REDLINE YARD",
    sub: "FILE // 2024 • STATE // ARCHIVED",
    clearance: "ACCÈS INTERNE",
    theatre: "SITE INDUSTRIEL",
    risk: "ÉLEVÉ",
    context: "Sécurisation d’un dépôt industriel partiellement occupé, utilisé comme point de rassemblement et de transit par plusieurs individus armés. Le terrain semblait ouvert, presque trop large pour inquiéter ; pourtant, chaque masse de ferraille, chaque empilement de conteneurs, chaque angle brisé transformait l’espace en mécanisme d’embuscade.",
    timeline: [
      "Reconnaissance extérieure et lecture des lignes de vue depuis les structures périphériques.",
      "Partition du site en secteurs d’intervention afin de limiter les angles de tir non contrôlés.",
      "Progression lente entre conteneurs, structures métalliques et zones de stockage encombrées.",
      "Contact bref avec présence hostile diffuse, sans engagement prolongé initial.",
      "Prise progressive du contrôle des axes centraux du dépôt.",
      "Vérification de bâtiments annexes et découverte de matériel abandonné sur site.",
      "Fin d’intervention après sécurisation complète et remise aux services compétents."
    ],
    outcome: "Zone stabilisée et rendue exploitable par les équipes d’enquête. Le dossier n’a pas l’éclat des opérations les plus visibles, mais il conserve quelque chose d’essentiel : la trace d’un travail lent, fatigant, rigoureux, où l’héroïsme n’a pris que la forme de la discipline maintenue jusqu’au bout.",
    arrest: "INTERPELLATIONS PARTIELLES",
    civilian: "ZONE PRÉALABLEMENT SÉCURISÉE",
    evidence: "OUTILS / MOYENS DE COMMUNICATION / VÉHICULE ABANDONNÉ",
    review: "OPÉRATION DE CONTRÔLE DU SITE VALIDÉE",
    dispatch: "Occupation diffuse signalée depuis trois accès distincts. Terrain jugé défavorable à l’assaut direct.",
    witness: "« On aurait dit un endroit vide, jusqu’au moment où ça a commencé à bouger partout à la fois. »",
    attachment: "ANNEXE 14-H SCELLÉE // CARTOGRAPHIE SECTORIELLE DU SITE",
    note: "Intervention retenue pour la qualité du découpage tactique du terrain."
  },

  civic_echo: {
    state: "ARCHIVED",
    system: "INCIDENT FILE // CIVIC ECHO // INTERNAL",
    title: "CIVIC ECHO",
    sub: "FILE // 2023 • STATE // ARCHIVED",
    clearance: "ACCÈS INTERNE",
    theatre: "BÂTIMENT CIVIQUE",
    risk: "MODÉRÉ",
    context: "Le signalement ne parlait d’abord que d’un bruit sourd, de portes refermées trop vite, d’un agent municipal introuvable. Rien qui justifie immédiatement une montée tactique, et pourtant assez pour faire sentir que le bâtiment n’était plus neutre. Les néons froids, les bureaux vides, les couloirs administratifs presque sans voix ont peu à peu transformé la progression en recherche abstraite.",
    timeline: [
      "Mise en place d’un périmètre discret autour du bâtiment municipal.",
      "Regroupement des personnels évacués afin d’établir une chronologie cohérente.",
      "Progression méthodique étage par étage dans une structure partiellement vidée.",
      "Contrôle des bureaux, archives et zones techniques avec visibilité limitée.",
      "Découverte d’un individu armé isolé dans une section administrative fermée.",
      "Maîtrise rapide sans échange prolongé de tirs.",
      "Vérification complète du site et levée progressive du dispositif."
    ],
    outcome: "Incident contenu sans panique générale ni blessé civil. Archivé, le dossier reste utile parce qu’il rappelle à quel point un lieu banal peut devenir instable dès qu’il cesse d’être lisible pour ceux qui y entrent.",
    arrest: "SUSPECT INTERPELLÉ VIVANT",
    civilian: "AUCUNE VICTIME CIVILE",
    evidence: "ARME DE POING / DOSSIERS OUVERTS / TÉLÉPHONE ENDOMMAGÉ",
    review: "INTERVENTION CONSIDÉRÉE COMME MAÎTRISÉE",
    dispatch: "Appel interne faible priorité requalifié en niveau tactique après disparition agent sur site.",
    witness: "« Le bâtiment faisait plus peur vide qu’il ne l’aurait fait plein. »",
    attachment: "ANNEXE 06-L SCELLÉE // CHRONOLOGIE PERSONNEL ÉVACUÉ",
    note: "Mission relue pour sa gestion du doute initial et de la montée graduelle du dispositif."
  },

  twin_palms: {
    state: "ARCHIVED",
    system: "INCIDENT FILE // TWIN PALMS // INTERNAL",
    title: "TWIN PALMS",
    sub: "FILE // 2025 • STATE // ARCHIVED",
    clearance: "ACCÈS INTERNE",
    theatre: "MOTEL PÉRIPHÉRIQUE",
    risk: "ÉLEVÉ",
    context: "Le motel avait ce visage de fin de route que connaissent toutes les villes : enseigne usée, parking trop éclairé, portes alignées derrière lesquelles chacun semble pouvoir disparaître sans bruit. Les renseignements parlaient d’armes, peut-être de plusieurs individus, peut-être d’une simple halte de transit. C’est toujours ce 'peut-être' qui rend les lieux de passage aussi dangereux.",
    timeline: [
      "Verrouillage discret du parking et repérage des accès latéraux du motel.",
      "Vérification silencieuse des chambres adjacentes afin d’isoler la zone d’intérêt.",
      "Annonce progressive et contrôle des ouvertures donnant sur la coursive principale.",
      "Réponse hostile depuis une chambre centrale et couverture immédiate de l’axe.",
      "Entrée rapide sur la zone concernée avec gestion simultanée des chambres voisines.",
      "Découverte d’armes et de matériel de déplacement dissimulés dans la chambre ciblée.",
      "Clôture de scène après extraction des occupants et sécurisation complète de la coursive."
    ],
    outcome: "Le site a été stabilisé sans propagation de la menace au reste du motel. Le dossier rappelle surtout la violence particulière des lieux provisoires : espaces trop petits, trop proches, où des vies ordinaires peuvent côtoyer le pire à seulement quelques mètres.",
    arrest: "PLUSIEURS OCCUPANTS INTERPELLÉS",
    civilian: "TÉMOINS CONFINÉS / AUCUN BLESSÉ CIVIL",
    evidence: "ARMES / PLAQUES / ESPÈCES / TÉLÉPHONES",
    review: "AUCUNE ANOMALIE RELEVÉE",
    dispatch: "Plaques non concordantes signalées sur parking. Chambre centrale identifiée comme point d’intérêt principal.",
    witness: "« On entendait la télévision d’une chambre et, juste à côté, quelque chose qui ne collait pas du tout. »",
    attachment: "ANNEXE 11-E SCELLÉE // PLAN COURSIVE ET CHAMBRES ADJACENTES",
    note: "Le cadre confiné en fait un dossier pédagogique pour l’intervention en hébergement de transit."
  },

  long_march: {
    state: "ARCHIVED",
    system: "INCIDENT FILE // LONG MARCH // INTERNAL",
    title: "LONG MARCH",
    sub: "FILE // 2023 • STATE // ARCHIVED",
    clearance: "ACCÈS INTERNE",
    theatre: "RÉSIDENCE COLLECTIVE",
    risk: "MODÉRÉ",
    context: "Il n’y avait pas d’ennemi clairement désigné au départ, seulement une cage d’escalier, des portes ouvertes, des appartements déjà fouillés par la peur et cette fatigue très particulière qui s’installe quand l’intervention dure plus que le rythme naturel du stress. LONG MARCH n’est pas un dossier spectaculaire : c’est précisément ce qui le rend précieux. Il montre comment une équipe tient dans la durée, non contre un éclat de violence, mais contre l’érosion lente de l’attention.",
    timeline: [
      "Sécurisation du hall et des accès latéraux de la résidence.",
      "Progression méthodique par paliers dans les parties communes dégradées.",
      "Vérification successive des appartements signalés comme ouverts ou abandonnés.",
      "Contacts intermittents avec occupants paniqués et témoins peu fiables.",
      "Localisation tardive de l’individu recherché dans un niveau supérieur partiellement vide.",
      "Maîtrise sans échange létal dans un couloir encombré.",
      "Stabilisation complète de l’immeuble et remise au dispositif local."
    ],
    outcome: "Le dossier n’a rien de spectaculaire, mais il reste lu pour une raison simple : il documente la manière dont la patience, la répétition et la rigueur peuvent parfois sauver davantage que la vitesse pure.",
    arrest: "SUSPECT INTERPELLÉ",
    civilian: "RÉSIDENTS MAINTENUS EN SÉCURITÉ",
    evidence: "ARME IMPROVISÉE / TÉLÉPHONE / VÊTEMENTS ABANDONNÉS",
    review: "INTERVENTION JUGÉE STABLE",
    dispatch: "Troubles répétés signalés sur plusieurs étages. Individu non localisé pendant phase initiale.",
    witness: "« On avait l’impression que le bâtiment respirait avec nous. Lentement, mal, mais encore. »",
    attachment: "ANNEXE 08-K SCELLÉE // NOTE DE FATIGUE OPÉRATIONNELLE",
    note: "Dossier conservé pour l’étude des progressions longues en habitat vertical dégradé."
  },

  static_breach: {
    state: "RESTRICTED",
    system: "INCIDENT FILE // STATIC BREACH // RESTRICTED",
    title: "STATIC BREACH",
    sub: "FILE // 2024 • STATE // RESTRICTED",
    clearance: "ACCÈS RESTREINT",
    theatre: "COMPLEXE INDUSTRIEL",
    risk: "SÉVÈRE",
    context: "Intervention déclenchée sur un complexe industriel occupé illégalement par un groupe armé retranché. Très tôt, il est apparu que le site ne répondrait à aucune logique simple : volumes trop vastes pour être fermés proprement, circulation sonore trompeuse, informations incomplètes, et présence hostile capable de disparaître d’une aile à l’autre sans jamais offrir une lecture claire de ses effectifs.",
    timeline: [
      "Établissement d’un périmètre élargi et coupure partielle des axes d’entrée du complexe.",
      "Reconnaissance des volumes intérieurs à partir d’informations incomplètes et de plans partiellement obsolètes.",
      "Progression tactique dans plusieurs zones fermées avec contact hostile intermittent.",
      "Réorganisation de la ligne d’assaut après constat d’une résistance plus structurée qu’anticipé.",
      "Maintien du contrôle sur les accès clefs pendant la durée de l’engagement.",
      "Décision de retrait tactique partiel afin d’éviter une escalade incontrôlée en structure dense.",
      "Sortie ordonnée des équipes et maintien du secteur sous surveillance renforcée."
    ],
    outcome: "Objectif partiellement atteint. Certains segments du site ont été contrôlés, mais jamais assez longtemps pour une exploitation complète. Le dossier reste restreint non seulement pour ce qu’il contient, mais aussi pour ce qu’il laisse en suspens.",
    arrest: "AUCUNE INTERPELLATION PRINCIPALE SÉCURISÉE",
    civilian: "AUCUNE PRÉSENCE CIVILE CONFIRMÉE",
    evidence: "RÉCUPÉRATION DE MATÉRIEL LIMITÉE",
    review: "RESTRICTED / DÉCISION TACTIQUE EN COURS D’EXAMEN",
    dispatch: "Premiers retours contradictoires sur effectifs hostiles. Lecture du site jugée incomplète dès phase 1.",
    witness: "« Chaque fois qu’on pensait avoir compris la forme du lieu, elle changeait. »",
    attachment: "ANNEXE 31-R SCELLÉE // SEGMENTS D’ENGAGEMENT HORS VERSION STANDARD",
    note: "Consultation restreinte. Les séquences d’engagement direct et les décisions de retrait restent soumises à contrôle interne."
  },

  blue_room: {
    state: "RESTRICTED",
    system: "INCIDENT FILE // BLUE ROOM // RESTRICTED",
    title: "BLUE ROOM",
    sub: "FILE // 2025 • STATE // RESTRICTED",
    clearance: "ACCÈS RESTREINT",
    theatre: "ÉTABLISSEMENT MÉDICAL",
    risk: "CRITIQUE",
    context: "Alerte armée sur site médical avec forte densité civile, circulation confuse et information initiale contradictoire. Dès l’arrivée, tout paraissait trop fragile pour supporter une erreur : familles dans les couloirs, personnel sous tension, alarmes, annonces incomplètes, et ce mélange d’urgence clinique et de peur brute qui rend chaque décision plus lourde qu’ailleurs.",
    timeline: [
      "Isolement progressif du bâtiment et évacuation sélective des zones directement exposées.",
      "Coordination étroite avec le personnel médical et la sécurité interne pour lecture des déplacements possibles.",
      "Progression en environnement sensible avec règles de tir strictes et priorité absolue à la protection des civils.",
      "Vérification de plusieurs salles et couloirs à visibilité réduite.",
      "Contact critique dans une zone de soins fermée nécessitant une décision immédiate.",
      "Neutralisation de la menace sans rupture générale du dispositif d’évacuation.",
      "Contrôle final de l’aile concernée et bascule vers phase d’enquête."
    ],
    outcome: "Menace stoppée. Civils protégés. Mais le dossier ne se résume pas à un dénouement tactique : il garde surtout la trace d’un lieu de soin traversé par la violence, et de la manière dont chaque geste a dû être mesuré à l’échelle humaine avant même d’être jugé tactiquement juste.",
    arrest: "SUSPECT NEUTRALISÉ / SCÈNE MISE SOUS SCELLÉS",
    civilian: "CIVILS ÉVACUÉS / AUCUN ÉVÉNEMENT DE MASSE",
    evidence: "ARME DE POING / EFFETS PERSONNELS / CAMÉRAS INTERNES",
    review: "RESTRICTED / EXAMEN DU COMMANDEMENT EN COURS",
    dispatch: "Appels multiples depuis aile médicale nord. Localisation suspecte instable avant contact final.",
    witness: "« Les gens pleuraient en silence pour ne pas attirer l’attention. C’est ce silence-là que je n’oublierai pas. »",
    attachment: "ANNEXE 44-M SCELLÉE // EXTRAITS VIDÉO SOUS RESTRICTION",
    note: "Accès limité. Les communications radio, les angles caméra et les annexes médicales associées au dossier ne figurent pas dans la version consultable."
  },

  crosswind: {
    state: "RESTRICTED",
    system: "INCIDENT FILE // CROSSWIND // RESTRICTED",
    title: "CROSSWIND",
    sub: "FILE // 2025 • STATE // RESTRICTED",
    clearance: "ACCÈS RESTREINT",
    theatre: "NŒUD AUTOROUTIER",
    risk: "CRITIQUE",
    context: "Le dossier commence dans un échangeur saturé par les véhicules stoppés, les appels d’urgence superposés et les informations qui se contredisent en temps réel. Un homme armé se déplace entre les files, disparaît derrière les glissières, réapparaît à contre-jour. Rien n’est stable : ni les lignes de vue, ni la position exacte de la menace, ni la capacité des civils à comprendre quoi faire.",
    timeline: [
      "Coupure partielle de l’échangeur et redirection d’urgence des flux encore mobiles.",
      "Repérage visuel intermittent de la menace au milieu des véhicules immobilisés.",
      "Mise à couvert progressive des automobilistes les plus exposés.",
      "Progression difficile entre carrosseries, glissières et angles morts multiples.",
      "Tentatives de verbalisation restées sans effet durable sur le suspect.",
      "Contact bref puis rupture de visibilité avant relocalisation finale.",
      "Neutralisation de la menace et reprise progressive du contrôle du secteur."
    ],
    outcome: "L’incident a été contenu sans basculer en événement de masse. Le rapport insiste sur la configuration exceptionnelle du terrain : un espace ouvert devenu plus étouffant qu’un intérieur.",
    arrest: "MENACE PRINCIPALE STOPPÉE",
    civilian: "PLUSIEURS CIVILS EXTRAITS / AUCUNE VICTIME DIRECTE",
    evidence: "ARME / TÉLÉPHONE / VÉHICULE ABANDONNÉ",
    review: "RESTRICTED / ANALYSE INTERNE MAINTENUE",
    dispatch: "Première circulation stoppée à 17:09. Menace mobile observée entre deux files de véhicules bloqués.",
    witness: "« On était entourés de voitures, mais on ne se sentait protégés par rien. »",
    attachment: "ANNEXE 28-W SCELLÉE // SCHÉMA DÉPLACEMENT MENACE",
    note: "Dossier classé sensible en raison du volume de témoins et des captations vidéo multiples."
  },

  saint_elias: {
    state: "RESTRICTED",
    system: "INCIDENT FILE // SAINT ELIAS // RESTRICTED",
    title: "SAINT ELIAS",
    sub: "FILE // 2024 • STATE // RESTRICTED",
    clearance: "ACCÈS RESTREINT",
    theatre: "SITE RELIGIEUX",
    risk: "SÉVÈRE",
    context: "Recherche d’un individu retranché dans un bâtiment religieux encore partiellement occupé. La difficulté n’était pas seulement opérationnelle : elle était symbolique, humaine, presque morale. Chaque mouvement devait être pesé contre la vulnérabilité des personnes présentes, contre la charge émotionnelle des témoins et contre ce que représente un tel lieu lorsqu’il cesse, même brièvement, d’être refuge pour devenir scène tactique.",
    timeline: [
      "Isolement discret des accès principaux sans provoquer de mouvement de panique.",
      "Évacuation partielle des personnes présentes avec appui des responsables du site.",
      "Lecture progressive de la structure intérieure et de ses volumes secondaires.",
      "Vérification d’espaces annexes à visibilité réduite et à acoustique trompeuse.",
      "Localisation tardive de l’individu dans une zone en retrait non accessible d’emblée.",
      "Stabilisation de la situation sans recours à une montée de force immédiate.",
      "Fin d’intervention après sécurisation complète du bâtiment et prise en charge du suspect."
    ],
    outcome: "Le site a été sécurisé et l’intervention s’est achevée sans blessé civil. Restreint, le dossier est souvent évoqué pour sa charge émotionnelle particulière et pour l’équilibre rare qu’il a fallu tenir entre fermeté tactique, retenue humaine et respect du lieu.",
    arrest: "SUSPECT INTERPELLÉ",
    civilian: "PERSONNES PRÉSENTES MISES EN SÉCURITÉ",
    evidence: "ARME / EFFETS PERSONNELS / NOTE MANUSCRITE",
    review: "RESTRICTED / VALIDATION HIÉRARCHIQUE MAINTENUE",
    dispatch: "Présence civile partielle confirmée sur site. Intervention requalifiée sensible avant engagement complet.",
    witness: "« Personne ne voulait croire que ça pouvait arriver ici. C’est peut-être pour ça que la peur a été si forte. »",
    attachment: "ANNEXE 19-S SCELLÉE // TÉMOIGNAGES HORS VERSION PUBLIABLE",
    note: "Consultation limitée. Le cadre sensible du site et plusieurs témoignages restent hors version standard."
  },

  winter_garden: {
    state: "RESTRICTED",
    system: "INCIDENT FILE // WINTER GARDEN // RESTRICTED",
    title: "WINTER GARDEN",
    sub: "FILE // 2025 • STATE // RESTRICTED",
    clearance: "ACCÈS RESTREINT",
    theatre: "SITE PUBLIC SENSIBLE",
    risk: "SÉVÈRE",
    context: "La serre municipale n’aurait jamais dû devenir une scène tactique. L’humidité brouillait l’air, les parois réfléchissaient la lumière, les silhouettes se déformaient entre les feuillages et les verrières. Le signalement d’une arme paraissait presque absurde dans un tel décor, jusqu’au moment où le décor lui-même s’est mis à servir de masque. L’intervention a obligé l’équipe à avancer dans un lieu fragile, vivant, presque paisible en apparence, alors même que la menace s’y déplaçait comme dans un théâtre construit pour l’effacement.",
    timeline: [
      "Isolement rapide des accès publics et mise à l’abri des visiteurs encore présents.",
      "Reconnaissance visuelle perturbée par condensation, végétation dense et reflets multiples.",
      "Progression lente entre zones de culture, allées étroites et structures métalliques internes.",
      "Détection intermittente de la menace dans les segments les plus humides de la serre principale.",
      "Tentative de verbalisation sans réponse exploitable.",
      "Contact final à proximité d’un local technique secondaire.",
      "Neutralisation de la situation et verrouillage complet du site pour exploitation."
    ],
    outcome: "Le site a été repris sans effondrement de la situation civile, mais l’opération a laissé à l’équipe une impression presque irréelle. Tout semblait trop calme pour contenir ce niveau de tension, et c’est précisément ce contraste qui en fait aujourd’hui un dossier à part.",
    arrest: "SUSPECT INTERPELLÉ APRÈS RÉSISTANCE BRÈVE",
    civilian: "VISITEURS MIS À L’ABRI / AUCUN BLESSÉ",
    evidence: "ARME DE POING / SAC / SUPPORTS PAPIER HUMIDES",
    review: "RESTRICTED / EXAMEN FINAL EN ATTENTE",
    dispatch: "Signalement armé jugé incertain au départ. Confirmation visuelle obtenue après fermeture partielle du site.",
    witness: "« On entendait l’eau tomber et pourtant tout le monde savait qu’autre chose bougeait là-dedans. »",
    attachment: "ANNEXE 52-G SCELLÉE // PHOTOGRAMMES PARTIELS ENVIRONNEMENT SERRE",
    note: "Dossier régulièrement mentionné pour les contraintes visuelles extrêmes en environnement civil atypique."
  }
};